spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:file:./h2db/books;time zone=UTC
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  mvc:
    log-request-details: 'true'
  jpa:
    properties:
      hibernate:
        generate_statistics: 'true'
        format_sql: 'true'
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
server:
  error:
    include-message: always
