spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:file:./h2db/books;time zone=UTC
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  mvc:
    log-request-details: 'true'

  jpa:
    properties:
      hibernate:
        generate_statistics: 'true'
        format_sql: 'true'
    show-sql: 'true'

logging:
  level:
    root: info

server:
  port: 443
  servlet:
    context-path: /
  error:
    include-message: always
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: password
