insert into author (author_id, version, name) values ('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'Hombergs, Tom');
insert into author (author_id, version, name) values ('f6791adc-6a03-4d9b-ad30-ef7fd0545c58', 'Brown, Simon');
insert into author (author_id, version, name) values ('b0a61cbf-aed7-44f2-86b8-d1414cf4ec3a', 'Gunter, Stuart');
insert into author (author_id, version, name) values ('69c40138-1246-4a33-98d2-be764301c9f0', 'Adzic, Gojko');
insert into author (author_id, version, name) values ('53ccafde-e889-4796-a55d-17f5d0e8b267', 'Brandolini, Alberto');
insert into author (author_id, version, name) values ('884a10b7-b5ba-4937-8476-016af188baaf', 'Brown, Simon');

-- insert into book (book_id_type, book_id, title) values ('URL', 'https://leanpub.com/humansvscomputers', 'Humans vs Computers');
-- insert into book_author (book_id_type, book_id, author_id) values ('URL', 'https://leanpub.com/humansvscomputers', '69c40138-1246-4a33-98d2-be764301c9f0');
-- insert into book_format (book_id_type, book_id, format) values ('URL', 'https://leanpub.com/humansvscomputers', 'EPUB');
-- insert into book (book_id_type, book_id, title) values ('URL', 'https://leanpub.com/get-your-hands-dirty-on-clean-architecture', 'Get Your Hands Dirty on Clean Architecture');
-- insert into book_author (book_id_type, book_id, author_id) values ('URL', 'https://leanpub.com/get-your-hands-dirty-on-clean-architecture', '531e071d-2ff7-4737-a2d8-c4e1e1d81f97');
-- insert into book_format (book_id_type, book_id, format) values ('URL', 'https://leanpub.com/get-your-hands-dirty-on-clean-architecture', 'EPUB');
-- insert into book (book_id_type, book_id, title) values ('URL', 'https://leanpub.com/wardley-maps', 'Wardley Maps');
-- insert into book_author (book_id_type, book_id, author_id) values ('URL', 'https://leanpub.com/wardley-maps', 'b0a61cbf-aed7-44f2-86b8-d1414cf4ec3a');
-- insert into book_format (book_id_type, book_id, format) values ('URL', 'https://leanpub.com/wardley-maps', 'EPUB');
-- insert into book (book_id_type, book_id, title) values ('URL', 'https://leanpub.com/visualising-software-architecture', 'Visualise, document and explore your software architecture');
-- insert into book_author (book_id_type, book_id, author_id) values ('URL', 'https://leanpub.com/visualising-software-architecture', '884a10b7-b5ba-4937-8476-016af188baaf');
-- insert into book_format (book_id_type, book_id, format) values ('URL', 'https://leanpub.com/visualising-software-architecture', 'EPUB');
-- insert into book (book_id_type, book_id, title) values ('URL', 'https://leanpub.com/software-architecture-for-developers', 'Technical leadership and the balance with agility');
-- insert into book_author (book_id_type, book_id, author_id) values ('URL', 'https://leanpub.com/software-architecture-for-developers', '884a10b7-b5ba-4937-8476-016af188baaf');
-- insert into book_format (book_id_type, book_id, format) values ('URL', 'https://leanpub.com/software-architecture-for-developers', 'EPUB');
-- insert into book (book_id_type, book_id, title) values ('URL', 'https://leanpub.com/introducing_eventstorming', 'Introducing EventStorming');
-- insert into book_author (book_id_type, book_id, author_id) values ('URL', 'https://leanpub.com/introducing_eventstorming', '53ccafde-e889-4796-a55d-17f5d0e8b267');
-- insert into book_format (book_id_type, book_id, format) values ('URL', 'https://leanpub.com/introducing_eventstorming', 'EPUB');

insert into site (author_id, name, url) values('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'LinkedIn', 'https://au.linkedin.com/in/thombergs');
insert into site (author_id, name, url) values('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'GitHub', 'https://github.com/thombergs');
insert into site (author_id, name, url) values('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'Twitter', 'https://twitter.com/tomhombergs');
insert into site (author_id, name, url) values('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'Home page', 'https://facebook.com/reflectoring');
insert into site (author_id, name, url) values('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'blog', 'https://www.freecodecamp.org/news/author/thombergs/');
insert into site (author_id, name, url) values('531e071d-2ff7-4737-a2d8-c4e1e1d81f97', 'Facebook', 'https://reflectoring.io/');
